name: Unit & Integration tests CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['10', '12']
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - name: log info
      run: pwd; ls -al db/;
    - name: Install npm dependencies
      run: npm install
    - name: Run npm test script
      run: npm run test
      env:
        CI: true
